spring:
    application:
      name: api-gateway

  # api gateway routes
    cloud:
      gateway:
        routes:
          - id : order-service
            uri: lb://ORDER-SERVICE
            predicates:
              - Path=/orders/**
          - id: inventory-service
            uri: lb://INVENTORY-SERVICE
            predicates:
                - Path=/inventory/**

  #eureka config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
